api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        # stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        csv: ['text/csv']
        html: ['text/html']

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header