vich_uploader:
    db_driver: orm

    mappings:
        certificates:
            uri_prefix: /images/certificates
            upload_destination: '%kernel.project_dir%/public/images/certificates'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
